# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 08:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 8, 27, 24, 686838, tzinfo=utc)),
        ),
    ]
