# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171016_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=b'i am done'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 17, 51, 51, 598317, tzinfo=utc)),
        ),
    ]
